version: "3.12"

services:
  web:
    build: .
    container_name: find_your_trip_bd_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn find_your_trip_bd.asgi:application -w 1 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: find_your_trip_bd_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: tripdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery --app=recommender worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  flower:
    image: mher/flower
    container_name: flower
    command: celery flower --persistent=True
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5566
    ports:
      - 5566:5566
    volumes:
      - flower_data:/data
    depends_on:
      - celery

  redis:
    image: redis:7-alpine

volumes:
  postgres_data:
  flower_data:
    driver: local


